version: '3.8'

services:
  bot:
    build: .
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finfeed
    ports:
      - "5432:5432"
